// Code originally generated by wire

package inject

import (
	"github.com/rancherlabs/support-tools/eks-ebs-enable/core/app"
	"github.com/rancherlabs/support-tools/eks-ebs-enable/core/ports"
	"github.com/rancherlabs/support-tools/eks-ebs-enable/infrastructure/aws"
	"github.com/rancherlabs/support-tools/eks-ebs-enable/infrastructure/rancher"
	"github.com/rancherlabs/support-tools/eks-ebs-enable/internal/config"
	"github.com/spf13/afero"
)

func CreateApp(cfg *config.Config) app.App {
	configRancherConfig := rancherConfig(cfg)
	rancherService := rancher.NewService(configRancherConfig)
	fs := afero.NewOsFs()
	awsClientService := aws.NewService()
	collection := createPortsCollection(rancherService, fs, awsClientService)
	appApp := app.New(collection)
	return appApp
}

func createPortsCollection(rancherSvc ports.RancherService, fs afero.Fs, aws2 ports.AWSClientService) *ports.Collection {
	return &ports.Collection{
		Rancher:    rancherSvc,
		FileSystem: fs,
		AWS:        aws2,
	}
}

func rancherConfig(cfg *config.Config) *config.RancherConfig {
	return &cfg.Rancher
}
