---
kind: pipeline
name: default-linux-amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: docker-build--bad-ingress-scanner
    image: plugins/docker
    settings:
      repo: rancher/bad-ingress-scanner
      tags:
        - ${DRONE_BUILD_NUMBER}
        - ${DRONE_COMMIT_BRANCH}
        - latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      context: ./bad-ingress-scanner/
      dockerfile: ./bad-ingress-scanner/Dockerfile
    when:
      branch: master
      event:
        include:
        - push

  - name: docker-build--rancher-metadata-syncer
    image: plugins/docker
    settings:
      repo: rancher/metadata-syncer
      tags:
        - ${DRONE_BUILD_NUMBER}
        - ${DRONE_COMMIT_BRANCH}
        - latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      context: ./rancher-metadata-syncer/
      dockerfile: ./rancher-metadata-syncer/Dockerfile
    when:
      branch: master
      event:
        include:
        - push

  - name: docker-build--change-nodetemplate-owner
    image: plugins/docker
    settings:
      repo: rancher/change-nodetemplate-owner
      tags:
        - ${DRONE_BUILD_NUMBER}
        - ${DRONE_COMMIT_BRANCH}
        - latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      context: ./change-nodetemplate-owner/
      dockerfile: ./change-nodetemplate-owner/Dockerfile
    when:
      branch: master
      event:
        include:
        - push

  - name: docker-build--etcd-tools
    image: plugins/docker
    settings:
      repo: rancher/etcd-tools
      tags:
        - ${DRONE_BUILD_NUMBER}
        - ${DRONE_COMMIT_BRANCH}
        - latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      context: ./etcd-tools/
      dockerfile: ./etcd-tools/Dockerfile
    when:
      branch: master
      event:
        include:
        - push

  - name: docker-build--system-info
    image: plugins/docker
    settings:
      repo: rancher/systems-info
      tags:
        - ${DRONE_BUILD_NUMBER}
        - ${DRONE_COMMIT_BRANCH}
        - latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      context: ./collection/rancher/v2.x/systems-information/
      dockerfile: ./collection/rancher/v2.x/systems-information/Dockerfile
    when:
      branch: master
      event:
        include:
        - push
