---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rancher-logs-collector
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rancher-logs-collector-read-only
  namespace: default
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    # We include 'list' and 'watch' because 'get' alone only allows 
    # fetching a single resource by its specific name.
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rancher-logs-collector-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: rancher-logs-collector
    namespace: default
roleRef:
  kind: ClusterRole
  name: rancher-logs-collector-read-only
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: Pod
metadata:
  name: rancher-logs-collector
  namespace: default
  labels:
    app: rancher-logs-collector
spec:
  serviceAccountName: rancher-logs-collector
  containers:
    - name: rancher-logs-collector
      image: rancherlabs/swiss-army-knife
      imagePullPolicy: IfNotPresent
  restartPolicy: Always